In [66]:
import numpy as np
#creating 2D array

a = np.array([[1,2],[3,5],[3,6]])
a

array([[1, 2],
       [3, 5],
       [3, 6]])

In [28]:
#dimension
a.ndim

2

In [29]:
#total no. of elements
a.size

6

In [30]:
#shape of array
a.shape

(3, 2)

In [31]:
#array all having zeroes/ones
print (np.zeros((3,4)))
print (np.ones((3,4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#array from arange

b = np.arange(2,5)
print(b)

c = np.arange(0,21,5)
print(c)

[2 3 4]
[ 0  5 10 15 20]


In [33]:
#creating 10 linearly spaced elements b/w 1,5
d = np.linspace(1,5,10)

print (d)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [43]:
#inverting rows and columns with each other using reshape
print(a)
f = a.reshape(2,3)
e = a.reshape(6,1)
print('\n',f)
print(e)
      

[[1 2]
 [3 5]
 [3 6]]

 [[1 2 3]
 [5 3 6]]
[[1]
 [2]
 [3]
 [5]
 [3]
 [6]]


In [46]:
#making n-D array as 1-D
g = a.ravel()
print(g)

[1 2 3 5 3 6]


In [50]:
print(a.min())
print(a.max())
print(a.std())
print(a.sum())

1
6
1.699673171197595
20


In [55]:
#adding axis wise
print(a.sum(axis = 0))
print(a.sum(axis = 1))

[ 7 13]
[3 8 9]


In [63]:
#operations on two arrays
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
b = np.array([[7,3,8],[3,1,2],[4,7,9]])

print(a)
print('\n')
print(b)
print('\n')

print (a+b)
print('\n')

print(a-b)
print('\n')



[[1 2 3]
 [3 4 5]
 [6 7 8]]


[[7 3 8]
 [3 1 2]
 [4 7 9]]


[[ 8  5 11]
 [ 6  5  7]
 [10 14 17]]


[[-6 -1 -5]
 [ 0  3  3]
 [ 2  0 -1]]




In [65]:
#matrix product
b = np.array([[7,8],[1,2],[5,3]])

print (a.dot(b))

[[24 21]
 [50 47]
 [89 86]]
