In [3]:
import numpy as np

a = np.arange(1,10).reshape(3,3)
print (a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
b = a > 3
print (b)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [9]:
#returning list of elements from a which are greater than 4
print (a[b])

[4 5 6 7 8 9]


In [11]:
#replacing the elments from a which are greater than 4 with 100
a[b]=100
print(a)

[[  1   2   3]
 [100 100 100]
 [100 100 100]]
