In [1]:
import numpy as np

n = np.arange(6)
n

array([0, 1, 2, 3, 4, 5])

In [6]:
#accessing..
print(n[0],n[-1],'\n',n[0:3],n[0:-1])

0 5 
 [0 1 2] [0 1 2 3 4]


In [11]:
#2D

a = np.arange(1,10).reshape(3,3)
print (a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#accessing...
print (a[1,2])
print('\n')
print(a[1:3,1])
print('\n')
print(a[1,1:3])
print('\n')
print(a[1:3,1:3])


6


[5 8]


[5 6]


[[5 6]
 [8 9]]


In [24]:
#Traversing...
for row in a:
    for column in row:
        print(column)
        
print('\n')

#OR

for cell in a.flat:
    print(cell)
    
#OR  
print('\n')   
for cell in a.ravel():
    print(cell)

1
2
3
4
5
6
7
8
9


1
2
3
4
5
6
7
8
9


1
2
3
4
5
6
7
8
9


In [30]:
#Stacking
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

print(a,'\n')
print(b,'\n')


#vertically
print(np.vstack((a,b)),'\n')

#horizontally
print(np.hstack((a,b)),'\n')


[[0 1]
 [2 3]
 [4 5]] 

[[ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]] 



In [36]:
#splitting...
print(np.hsplit(a,2))
print(np.vsplit(a,3))

[array([[0],
       [2],
       [4]]), array([[1],
       [3],
       [5]])]
[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]
