In [3]:
import numpy as np

a = np.arange(1,13).reshape(4,3)

print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#printing row wise
for x in np.nditer(a,order = 'C'):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
#printing column wise
for x in np.nditer(a,order = 'F'):
    print(x)

1
4
7
10
2
5
8
11
3
6
9
12


In [11]:
#printing lists of columns
for x in np.nditer(a, order = 'F',flags = ['external_loop']):
    print(x)

[ 1  4  7 10]
[ 2  5  8 11]
[ 3  6  9 12]


In [14]:
#printing lists of rows
for x in np.nditer(a, order = 'C',flags = ['external_loop']):
    print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#reading and writing into the array using nditer
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x**2
print(a)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
